characters = {
    "Fighter":
    {
        "name":"Fighter",
        "HP":100,
        "attack":5,
        "defence":10
    },
    "Defender":
    {
        "name":"Defender",
        "HP":140,
        "attack":3,
        "defence":15
    },
    "Mag":
    {
        "name":"Mag",
        "HP":80,
        "attack":9,
        "defence":6
    },
    "Bowman":
    {
        "name":"Bowman",
        "HP":100,
        "attack":7,
        "defence":7
    }
}